# Generated by Django 4.1.1 on 2022-10-03 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Название проекта длинной до 255 символов', max_length=255, unique=True, verbose_name='Название проекта')),
                ('url_repo', models.URLField(help_text='Сылка не репозиторий длинной до 200 символов', unique=True, verbose_name='Ссылка на репозиторий')),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Работники на проекте')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст заметки длинной до 511 символов', max_length='511', verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время редактирования')),
                ('is_active', models.BooleanField(default=False, verbose_name='Запись активна')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project', verbose_name='Проект')),
            ],
        ),
    ]
