# Generated by Django 4.1.1 on 2022-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='project',
            name='url_repo',
            field=models.URLField(blank=True, help_text='Сылка не репозиторий длинной до 200 символов', null=True, unique=True, verbose_name='Ссылка на репозиторий'),
        ),
    ]
