# Generated by Django 4.1.1 on 2022-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_project_url_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_repo',
            field=models.URLField(blank=True, help_text='Сылка не репозиторий длинной до 200 символов', null=True, unique=True, verbose_name='Ссылка на репозиторий'),
        ),
    ]
