# Generated by Django 4.1.1 on 2022-10-04 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_project_url_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_repo',
            field=models.URLField(blank=True, default=django.utils.timezone.now, help_text='Сылка не репозиторий длинной до 200 символов', unique=True, verbose_name='Ссылка на репозиторий'),
            preserve_default=False,
        ),
    ]
