# Generated by Django 4.1.1 on 2022-11-13 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0006_alter_project_url_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Работники на проекте'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(help_text='Текст заметки', verbose_name='Текст заметки'),
        ),
    ]
